package com.htyw.app.checkingIN.dao;

import java.util.List;

import com.htyw.app.checkingIN.pojo.CheckingInConfiguration;
import com.htyw.app.checkingIN.pojo.CheckingInConfigurationExample;

public interface CheckingInConfigurationDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checking_in_configuration
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checking_in_configuration
     *
     * @mbg.generated
     */
    int insert(CheckingInConfiguration record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checking_in_configuration
     *
     * @mbg.generated
     */
    int insertSelective(CheckingInConfiguration record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checking_in_configuration
     *
     * @mbg.generated
     */
    List<CheckingInConfiguration> selectByExample(CheckingInConfigurationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checking_in_configuration
     *
     * @mbg.generated
     */
    CheckingInConfiguration selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checking_in_configuration
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CheckingInConfiguration record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checking_in_configuration
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CheckingInConfiguration record);
    

	List<CheckingInConfiguration> selectJingWeiDu(Long TENANTID);
}